from typing import Protocol

class FlightEndpoint(Protocol):
    """Mission-level execution boundary. Unity implements this today; hardware must retain supervisory safety."""
    telemetry: dict | None
    events: object
    @property
    def connected(self) -> bool: ...
    async def command(self, action: str, parameters: dict | None = None, timeout: float = 240) -> dict: ...
    async def wait_tick(self, tick: int, timeout: float = 15) -> dict: ...
    async def capture(self, look: dict) -> dict: ...
